### ISSUE TITLE
Licença (livre)

### ISSUE THREAD

**Issue by nazareno** [thayannevls/BrasisDoBrasil#16]
adicionar licença do código aqui no repo

**Comment by andresmrm** [comment]
Bem lembrado! Obrigado!

Pessoal, sugiro a AGPL. Que, assim como a GPL, obriga quem fizer derivações do
código a mantê-lo aberto também. Mas a AGPL é mais recente e protege melhor
códigos que rodam online como o nosso.
Alguém se opõem?

**Comment by thayannevls** [comment]
Pode ser @andresmrm
